# NLP Practical — NLTK → Transformers

A complete progressive notebook: classical NLP preprocessing with **NLTK**, then modern NLP with **Hugging Face Transformers** — embeddings, attention, and the major Transformer tasks.

Run top to bottom in Google Colab or Jupyter.

# NLP Practical — NLTK → Transformers

### 1. Install the libraries

In [1]:
!pip install -q nltk transformers torch

---

# Part 1 — Basic NLP with NLTK

## 2. Import libraries

In [2]:
import nltk

from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk import pos_tag, ne_chunk

Download the required NLTK resources:

In [3]:
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")
nltk.download("averaged_perceptron_tagger")
nltk.download("averaged_perceptron_tagger_eng")
nltk.download("maxent_ne_chunker")
nltk.download("maxent_ne_chunker_tab")
nltk.download("words")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data] Downloading package maxent_ne_chunker to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping chunkers/maxent_ne_chunker.zip.
[nltk_data] Downloading package maxent_ne_chunker_tab to
[nltk_data]   

True

---

# 3. Raw text

Start with a sentence that contains several NLP concepts:

In [4]:
text = """
Ali is studying Artificial Intelligence at UET Peshawar.
He loves Natural Language Processing because it allows computers
to understand human language.
"""

print(text)


Ali is studying Artificial Intelligence at UET Peshawar.
He loves Natural Language Processing because it allows computers
to understand human language.



This is how the computer initially receives the text: simply as a string.

---

# 4. Sentence Tokenization

In [5]:
sentences = sent_tokenize(text)

print(sentences)

['\nAli is studying Artificial Intelligence at UET Peshawar.', 'He loves Natural Language Processing because it allows computers\nto understand human language.']


**Sentence tokenization divides a document into individual sentences.**

---

# 5. Word Tokenization

In [6]:
words = word_tokenize(text)

print(words)

['Ali', 'is', 'studying', 'Artificial', 'Intelligence', 'at', 'UET', 'Peshawar', '.', 'He', 'loves', 'Natural', 'Language', 'Processing', 'because', 'it', 'allows', 'computers', 'to', 'understand', 'human', 'language', '.']


**Word tokenization divides text into individual tokens.**

---

# 6. Lowercasing

In [7]:
words_lower = [word.lower() for word in words]

print(words_lower)

['ali', 'is', 'studying', 'artificial', 'intelligence', 'at', 'uet', 'peshawar', '.', 'he', 'loves', 'natural', 'language', 'processing', 'because', 'it', 'allows', 'computers', 'to', 'understand', 'human', 'language', '.']


For example, `Artificial` becomes `artificial`, `Intelligence` becomes `intelligence`. `Apple`, `apple`, and `APPLE` may represent the same word depending on the task.

---

# 7. Remove punctuation

In [8]:
import string

words_clean = [
    word for word in words_lower
    if word not in string.punctuation
]

print(words_clean)

['ali', 'is', 'studying', 'artificial', 'intelligence', 'at', 'uet', 'peshawar', 'he', 'loves', 'natural', 'language', 'processing', 'because', 'it', 'allows', 'computers', 'to', 'understand', 'human', 'language']


---

# 8. Stopword Removal

First see the stopwords:

In [9]:
stop_words = set(stopwords.words("english"))

print(list(stop_words)[:30])

['shouldn', 'most', 'needn', 'then', "they'd", "we'd", 'again', 'has', "they've", "you're", 'yourselves', 's', 'against', 'can', 'themselves', 'as', "aren't", "needn't", 'but', 'after', 'm', "i'm", "you've", "mightn't", 'hers', 'through', 'ours', 'our', "wasn't", 'what']


Now remove them:

In [10]:
filtered_words = [
    word for word in words_clean
    if word not in stop_words
]

print(filtered_words)

['ali', 'studying', 'artificial', 'intelligence', 'uet', 'peshawar', 'loves', 'natural', 'language', 'processing', 'allows', 'computers', 'understand', 'human', 'language']


For example, "is", "the", "to", "and" may be removed.

**Stopwords are commonly occurring words that may contribute little useful information for some NLP tasks.**

Important: we don't always remove stopwords. Modern Transformer models generally use the full tokenized input rather than manually deleting stopwords.

---

# Part 2 — Stemming

## 9. Porter Stemmer

In [11]:
stemmer = PorterStemmer()

words = [
    "play",
    "playing",
    "played",
    "plays",
    "studies",
    "studying",
    "easily"
]

for word in words:
    print(word, "→", stemmer.stem(word))

play → play
playing → play
played → play
plays → play
studies → studi
studying → studi
easily → easili


**Stemming mechanically reduces words to a stem, and the resulting stem may not be a valid English word.**

---

# Part 3 — Lemmatization

## 10. WordNet Lemmatizer

In [12]:
lemmatizer = WordNetLemmatizer()

words = [
    "playing",
    "played",
    "plays",
    "studies",
    "studying",
    "mice"
]

for word in words:
    print(word, "→", lemmatizer.lemmatize(word))

playing → playing
played → played
plays → play
studies → study
studying → studying
mice → mouse


For better results, give the appropriate POS:

In [13]:
print(lemmatizer.lemmatize("studies", pos="v"))
print(lemmatizer.lemmatize("playing", pos="v"))
print(lemmatizer.lemmatize("mice", pos="n"))

study
play
mouse


Compare: Stemming gives `studies → studi`, while Lemmatization gives `studies → study`.

---

# Part 4 — POS Tagging

## 11. Part-of-Speech Tagging

In [14]:
sentence = "Ali is studying Artificial Intelligence."

tokens = word_tokenize(sentence)

pos_tags = pos_tag(tokens)

print(pos_tags)

[('Ali', 'NNP'), ('is', 'VBZ'), ('studying', 'VBG'), ('Artificial', 'JJ'), ('Intelligence', 'NNP'), ('.', '.')]


Common tags: `NN` → noun, `VB` → verb, `JJ` → adjective, `RB` → adverb, `PRP` → pronoun. The exact tags depend on the tagger and context.

---

# Part 5 — Named Entity Recognition

## 12. NER with NLTK

In [15]:
sentence = """
Ali is studying at UET Peshawar and wants to work at Google.
"""

tokens = word_tokenize(sentence)

pos_tags = pos_tag(tokens)

tree = ne_chunk(pos_tags)

print(tree)

(S
  (GPE Ali/NNP)
  is/VBZ
  studying/VBG
  at/IN
  (ORGANIZATION UET/NNP Peshawar/NNP)
  and/CC
  wants/VBZ
  to/TO
  work/VB
  at/IN
  (ORGANIZATION Google/NNP)
  ./.)


NLTK may identify entities such as Ali → PERSON, UET Peshawar → ORGANIZATION, Google → ORGANIZATION.

**Named Entity Recognition identifies important entities such as people, organizations, locations, dates, etc.**

---

# Part 6 — The Important Problem

We have converted the sentence into tokens. But can a neural network understand these words? **No.** Computers ultimately need numerical representations.

```text
Human Language
      ↓
Tokens
      ↓
Numbers
      ↓
Machine Learning
```

This is the bridge to modern NLP.

---

# Part 7 — Introduce Transformers

Now move to Hugging Face. Instead of manually building every component, we can use a pretrained Transformer model.

In [16]:
from transformers import pipeline

---

# 8. Sentiment Analysis

In [17]:
from transformers import pipeline

sentiment = pipeline("sentiment-analysis")

result = sentiment(
    "I really love learning Natural Language Processing!"
)

print(result)

[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

[{'label': 'POSITIVE', 'score': 0.9997652173042297}]


The model receives text and predicts its sentiment.

---

# 9. Try multiple sentences

In [18]:
sentences = [
    "I love this movie.",
    "This movie is amazing.",
    "I hate this movie.",
    "This was a terrible experience."
]

results = sentiment(sentences)

for sentence, result in zip(sentences, results):
    print(sentence)
    print(result)
    print()

I love this movie.
{'label': 'POSITIVE', 'score': 0.9998736381530762}

This movie is amazing.
{'label': 'POSITIVE', 'score': 0.9998838901519775}

I hate this movie.
{'label': 'NEGATIVE', 'score': 0.9996869564056396}

This was a terrible experience.
{'label': 'NEGATIVE', 'score': 0.9989833235740662}



Now students can actually see an NLP model working.

---

# Part 8 — Tokenizer

This is **very important** before teaching Transformer architecture.

In [19]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(
    "bert-base-uncased"
)

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [20]:
text = "I love Natural Language Processing."

tokens = tokenizer.tokenize(text)

print(tokens)

['i', 'love', 'natural', 'language', 'processing', '.']


**A Transformer does not directly receive raw English. It receives tokens represented as numerical IDs.**

---

# 10. Convert tokens to IDs

In [21]:
token_ids = tokenizer.convert_tokens_to_ids(tokens)

print(token_ids)

[1045, 2293, 3019, 2653, 6364, 1012]


The exact IDs depend on the tokenizer/vocabulary.

```text
Text
 ↓
Tokens
 ↓
Token IDs
 ↓
Transformer
```

---

# 11. Let the tokenizer do everything

In [23]:
inputs = tokenizer(
    "I love Natural Language Processing.",
    return_tensors="pt"
)

print(inputs)

{'input_ids': tensor([[ 101, 1045, 2293, 3019, 2653, 6364, 1012,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1]])}


You will see fields such as `input_ids` and `attention_mask`.

- **input_ids**: The numerical representation of tokens.
- **attention_mask**: Tells the model which positions contain actual input tokens versus padding.

---

# Part 9 — Understand Special Tokens

In [24]:
text = "I love NLP."

encoded = tokenizer(
    text,
    return_tensors="pt"
)

print(encoded["input_ids"])

tensor([[  101,  1045,  2293, 17953,  2361,  1012,   102]])


Decode it:

In [25]:
print(
    tokenizer.convert_ids_to_tokens(
        encoded["input_ids"][0]
    )
)

['[CLS]', 'i', 'love', 'nl', '##p', '.', '[SEP]']


For BERT, you'll typically see special tokens `[CLS]`, `i`, `love`, `nlp`, `.`, `[SEP]`. `[CLS]` is a special classification token; `[SEP]` separates/end-marks sequences.

---

# Part 10 — WordPiece Tokenization

In [26]:
text = "unbelievable"

print(tokenizer.tokenize(text))

['unbelievable']


In [27]:
words = [
    "playing",
    "unbelievable",
    "internationalization",
    "happiness"
]

for word in words:
    print(word, "→", tokenizer.tokenize(word))

playing → ['playing']
unbelievable → ['unbelievable']
internationalization → ['international', '##ization']
happiness → ['happiness']


**Transformers often use subword tokenization, so a word doesn't necessarily correspond to one token.** This is an important difference from the simple `word_tokenize()` students learned with NLTK.

---

# Part 11 — Attention Mask

In [28]:
texts = [
    "I love NLP.",
    "I love machine learning."
]

encoded = tokenizer(
    texts,
    padding=True,
    return_tensors="pt"
)

print("Input IDs:")
print(encoded["input_ids"])

print("\nAttention Mask:")
print(encoded["attention_mask"])

Input IDs:
tensor([[  101,  1045,  2293, 17953,  2361,  1012,   102],
        [  101,  1045,  2293,  3698,  4083,  1012,   102]])

Attention Mask:
tensor([[1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1]])


`1` means real token, `0` means padding.

---

# Part 12 — Transformer Classification

In [29]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

model_name = "distilbert-base-uncased-finetuned-sst-2-english"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForSequenceClassification.from_pretrained(
    model_name
)

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

In [30]:
text = "I really enjoyed this course."

inputs = tokenizer(
    text,
    return_tensors="pt"
)

print(inputs)

{'input_ids': tensor([[ 101, 1045, 2428, 5632, 2023, 2607, 1012,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1]])}


In [31]:
outputs = model(**inputs)

print(outputs.logits)

tensor([[-4.3516,  4.6418]], grad_fn=<AddmmBackward0>)


---

# Part 13 — Convert Logits to Probabilities

In [32]:
import torch

probabilities = torch.softmax(
    outputs.logits,
    dim=-1
)

print(probabilities)

tensor([[1.2421e-04, 9.9988e-01]], grad_fn=<SoftmaxBackward0>)


In [33]:
predicted_class = torch.argmax(
    probabilities,
    dim=-1
)

print(predicted_class)

tensor([1])


In [34]:
print(model.config.id2label)

{0: 'NEGATIVE', 1: 'POSITIVE'}


```text
"I really enjoyed this course."
            ↓
       Tokenization
            ↓
        Token IDs
            ↓
          BERT
            ↓
          Logits
            ↓
        Softmax
            ↓
      POSITIVE
```

---

# Part 14 — Compare NLTK vs Transformers

| NLTK                            | Transformers                        |
| -------------------------------- | ------------------------------------ |
| Mainly NLP toolkit               | Deep-learning model ecosystem        |
| Tokenization                     | Tokenization                         |
| Stopword removal                 | Usually not manually removed         |
| Stemming                         | Generally not used                   |
| Lemmatization                    | Generally not used as preprocessing  |
| POS tagging                      | Can perform NLP tasks                |
| Classical NLP workflows          | Modern neural NLP                    |
| Rule/statistical tools           | Transformer architectures            |
| Usually build pipeline yourself  | Can use pretrained models            |

**NLTK teaches us how language can be processed. Transformers show us how modern neural networks can learn language representations and perform NLP tasks.**

---

# Part 15 — The Big Evolution

```text
                 NLP
                  │
        ┌─────────┴─────────┐
        │                   │
   Classical NLP       Neural NLP
        │                   │
      NLTK              RNN / LSTM / GRU
        │                   │
   Tokenization              ↓
   Stemming              Attention
   Lemmatization              ↓
   POS Tagging           Transformer
   NER                       │
                             ├── BERT
                             ├── GPT
                             ├── T5
                             └── LLMs
```

Final mental model:

```text
RAW TEXT
   ↓
Tokenization
   ↓
Numerical Representation
   ↓
Model
   ↓
Prediction / Generation
```

For **classical NLP**:

```text
Text
 ↓
NLTK preprocessing
 ↓
TF-IDF / features
 ↓
ML algorithm
 ↓
Prediction
```

For **modern Transformer NLP**:

```text
Text
 ↓
Transformer Tokenizer
 ↓
Token IDs + Attention Mask
 ↓
Embeddings
 ↓
Self-Attention
 ↓
Multi-Head Attention
 ↓
Transformer Layers
 ↓
Prediction / Generation
```

### ⭐ The key teaching point

Don't teach NLTK and Transformers as two unrelated libraries. Teach the students the **evolution**:

**Raw text → preprocessing → numerical representation → RNN/LSTM/GRU → limitations → attention → self-attention → multi-head attention → Transformer → BERT/GPT/LLMs.**

That storyline will make the Transformer architecture much easier for them to understand.

# NLP Practical — Extended Concepts (Part 16 onward)

This continues the same progressive notebook: **NLTK → Transformers**, adding the concepts that naturally come next in the storyline (embeddings, similarity, sequence models, attention internals, and more Transformer tasks).

---

# Part 16 — Bag of Words (Before Embeddings)

Before jumping to embeddings, show students the "naive" numerical representation.

In [35]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    "I love NLP",
    "I love machine learning",
    "NLP is fun"
]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

print(vectorizer.get_feature_names_out())
print(X.toarray())

['fun' 'is' 'learning' 'love' 'machine' 'nlp']
[[0 0 0 1 0 1]
 [0 0 1 1 1 0]
 [1 1 0 0 0 1]]


Explain:

> **Bag of Words counts word occurrences but ignores order and meaning.**

---

# Part 17 — TF-IDF

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(corpus)

print(tfidf.get_feature_names_out())
print(X_tfidf.toarray())

['fun' 'is' 'learning' 'love' 'machine' 'nlp']
[[0.         0.         0.         0.70710678 0.         0.70710678]
 [0.         0.         0.62276601 0.4736296  0.62276601 0.        ]
 [0.62276601 0.62276601 0.         0.         0.         0.4736296 ]]


Explain:

> **TF-IDF downweights very common words and upweights words that are distinctive to a document.**

This is the classical bridge between "tokens" and "numbers" that pre-dates Transformers.

---

# Part 18 — Word Embeddings (Word2Vec)

In [37]:
!pip install -q gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 50.5 MB/s eta 0:00:00


In [38]:
from gensim.models import Word2Vec

sentences = [
    ["ali", "loves", "nlp"],
    ["ali", "studies", "ai"],
    ["nlp", "is", "part", "of", "ai"]
]

model = Word2Vec(sentences, vector_size=50, window=3, min_count=1)

print(model.wv["nlp"])

[-0.01631583  0.0089916  -0.00827415  0.00164907  0.01699724 -0.00892435
  0.009035   -0.01357392 -0.00709698  0.01879702 -0.00315531  0.00064274
 -0.00828126 -0.01536538 -0.00301602  0.00493959 -0.00177605  0.01106732
 -0.00548595  0.00452013  0.01091159  0.01669191 -0.00290748 -0.01841629
  0.0087411   0.00114357  0.01488382 -0.00162657 -0.00527683 -0.01750602
 -0.00171311  0.00565313  0.01080286  0.01410531 -0.01140624  0.00371764
  0.01217773 -0.0095961  -0.00621452  0.01359526  0.00326295  0.00037983
  0.00694727  0.00043555  0.01923765  0.01012121 -0.01783478 -0.01408312
  0.00180291  0.01278507]


Explain:

> **Unlike Bag of Words, embeddings place words in a continuous vector space where similar words end up close together.**

Show similarity:

In [39]:
print(model.wv.most_similar("nlp"))

[('part', 0.12486250698566437), ('studies', 0.07399576157331467), ('ai', 0.04237300902605057), ('is', 0.018277151510119438), ('ali', 0.011071980930864811), ('of', -0.17424818873405457), ('loves', -0.1754782646894455)]


---

# Part 19 — Cosine Similarity Between Words

In [40]:
import numpy as np

def cosine_similarity(v1, v2):
    return np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))

vec1 = model.wv["nlp"]
vec2 = model.wv["ai"]

print(cosine_similarity(vec1, vec2))

0.042373016


Explain:

> **Cosine similarity measures how close two vectors point in the same direction — the standard way to compare embeddings.**

---

# Part 20 — Sentence Embeddings with Transformers

Now connect embeddings to Hugging Face.

In [41]:
!pip install -q sentence-transformers

In [42]:
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer("all-MiniLM-L6-v2")

sentence1 = "I love studying Natural Language Processing."
sentence2 = "NLP is my favorite subject."
sentence3 = "The weather is nice today."

embeddings = model.encode([sentence1, sentence2, sentence3])

print(util.cos_sim(embeddings[0], embeddings[1]))
print(util.cos_sim(embeddings[0], embeddings[2]))

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

tensor([[0.6816]])
tensor([[0.0113]])




# Part 24 — Zero-Shot Classification

A great "wow" moment: classify text into labels the model was never explicitly trained on.

In [46]:
from transformers import pipeline

classifier = pipeline("zero-shot-classification")

result = classifier(
    "Ali is studying Artificial Intelligence at UET Peshawar.",
    candidate_labels=["education", "sports", "politics", "technology"]
)

print(result)

[transformers] No model was supplied, defaulted to facebook/bart-large-mnli and revision d7645e1.
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/1.15k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.63GB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/515 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

{'sequence': 'Ali is studying Artificial Intelligence at UET Peshawar.', 'labels': ['technology', 'education', 'sports', 'politics'], 'scores': [0.9416881203651428, 0.04549540579319, 0.00792146846652031, 0.004895019810646772]}


Explain:

> **The model reasons about label meaning using the same embedding space it learned language in — no task-specific training required.**

---

# Part 25 — Text Generation (GPT-style)

In [50]:
generator = pipeline("text-generation", model="gpt2")

result = generator(
    "Natural Language Processing is",
    max_length=30,
    num_return_sequences=1
)

print(result[0]["generated_text"])

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

[transformers] Both `max_new_tokens` (=256) and `max_length`(=30) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


Natural Language Processing is a language design language.

The program is developed with the goal of developing a new type of language that will be suitable for everyday use. This type of language is not only suitable for use in everyday practice, but also for learning, as well as for the learning and learning-oriented activities.

The design of the language is based on the principles of the basic principles of functional programming and is based on the principles of the programming languages of languages development.

The program is designed to be used by people from all parts of the world, especially in the field of computer science.

The program consists of 32 modules, and consists of 32 languages designed for use in the language.

The module design consists of the following parts:

The language itself consists of 26 modules

The language is written in the following languages:

C++

Java

C#

C++

JavaScript

Python

JavaScript is a programming language that was introduced in 2006 

Explain:

> **Generation works by repeatedly predicting the next token and feeding it back in — the same input_ids/attention_mask machinery, used autoregressively.**

---

# Part 26 — Question Answering

Explain:

> **The model doesn't "search" the text like a database — it predicts the start and end token positions of the answer span.**

---

# Part 27 — Summarization

Explain:

> **Translation is a sequence-to-sequence task: an encoder reads the source sentence, a decoder generates the target sentence token by token.**

---

# Part 29 — Transformer NER (Compare to Part 5)

Now revisit Named Entity Recognition, but with a Transformer, so students can directly compare to NLTK's `ne_chunk`.

In [60]:
from transformers import pipeline

ner = pipeline(
    "ner",
    model="dbmdz/bert-large-cased-finetuned-conll03-english",
    aggregation_strategy="simple"
)

text = "Ali studies at UET Peshawar and wants to work at Google."

result = ner(text)

for entity in result:
    print(entity)

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

[transformers] BertForTokenClassification LOAD REPORT from: dbmdz/bert-large-cased-finetuned-conll03-english
Key                      | Status     |  | 
-------------------------+------------+--+-
bert.pooler.dense.bias   | UNEXPECTED |  | 
bert.pooler.dense.weight | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


{'entity_group': 'PER', 'score': np.float32(0.9984086), 'word': 'Ali', 'start': 0, 'end': 3}
{'entity_group': 'ORG', 'score': np.float32(0.99107194), 'word': 'UET P', 'start': 15, 'end': 20}
{'entity_group': 'LOC', 'score': np.float32(0.9131667), 'word': '##eshawar', 'start': 20, 'end': 27}
{'entity_group': 'ORG', 'score': np.float32(0.99905866), 'word': 'Google', 'start': 49, 'end': 55}


Explain:

> **Compare this to Part 5's NLTK output — the Transformer version is usually far more accurate and doesn't need hand-built grammar rules.**

---

# Part 30 — Fine-Tuning, Conceptually

Students don't need to run full fine-tuning in class, but they should understand the idea before moving on.

```text
Pretrained model (knows language in general)
          +
Small labeled dataset (your specific task)
          ↓
   Fine-tuning (few epochs, small learning rate)
          ↓
   Task-specific model
```

In [61]:
from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    learning_rate=2e-5
)

print(training_args)

TrainingArguments(
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_in_order=True,
dataloader_multiprocessing_context=None,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_static_graph=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=False,
do_predict=False,
do_train=False,
enable_jit_checkpoint=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_star

Explain:

> **Fine-tuning adjusts the pretrained weights slightly instead of learning from scratch — this is why it works with much less data than training a model from zero.**

---

# Part 31 — Updated Comparison Table

| Concept | Classical NLP (NLTK) | Modern NLP (Transformers) |
|---|---|---|
| Text → numbers | Bag of Words / TF-IDF | Token IDs → learned embeddings |
| Word meaning | Not captured | Captured via embeddings (Word2Vec, contextual embeddings) |
| Context sensitivity | None (word counts are static) | Full (self-attention, contextual) |
| Sequence handling | N/A | RNN/LSTM (sequential) → Transformer (parallel, attention-based) |
| Similarity | Cosine similarity on TF-IDF vectors | Cosine similarity on dense embeddings |
| New tasks | Requires new feature engineering | Zero-shot classification, prompting |
| Long documents | Struggles (sparse, no order) | Handles well (attention over full context) |

---

# Part 32 — Updated Big Picture Diagram

```text
RAW TEXT
   │
   ▼
Tokenization (NLTK: word_tokenize | Transformers: subword tokenizer)
   │
   ▼
Numerical Representation
   ├── Classical: Bag of Words / TF-IDF (sparse, no meaning)
   └── Modern: Token embeddings (dense, learned meaning)
   │
   ▼
Sequence Modeling
   ├── RNN / LSTM / GRU (sequential, forgets long context)
   └── Self-Attention → Multi-Head Attention (parallel, full context)
   │
   ▼
Transformer Layers (stacked attention + feed-forward blocks)
   │
   ▼
Task Head
   ├── Classification (sentiment, zero-shot)
   ├── Span extraction (question answering)
   ├── Sequence-to-sequence (translation, summarization)
   └── Autoregressive generation (GPT-style)
   │
   ▼
Prediction / Generated Text
```